* Permutations
Given a number, rearrange the digits of that number to make a higher number, among all such permutations that are greater,one of them is the smallest, Find the smallest greater permutation (the next Permutation).

Examples:
next_permutation (12) = 21
next_permutation (315) = 351
next_permutation (583) = 835
next_permutation (12389) = 12398
next_permutation (34722641) = 34724126

* Binary tree
Given a binary tree, where each node represents an integer, find the max value of path sum.

* Finding islands

Q: Find number of Islands.
XXXOO
OOOXX
XXOOX
Return 3 islands.
1 1 1OO
OOO2 2
3 3OO 2


Followup: If the board is too big to fit in memory, how to get the number?

* Interleave list
Interleave list of lists in Java
Example:
input = [[1,2,3], [9, 0], [5], [-4,-5,-2,-3,-1]];
output = [1,9,5,-4,2,0,-5,3,-2,-3,-1]

* Find sum
Given an array of n elements return true if 3 of the sum of 3 elements is equal to a constant c

Example array a[6,2,3,4] constant c = 9

if a[1] + [2] + [3] == c return true

The size of the array is n

If any set of 3 elements is equal to the constant c, then return false

* String parenthesis balancing
Given a string with alpha-numeric characters and parentheses, return a string with balanced parentheses by removing the fewest characters possible. You cannot add anything to the string.

* Distance
Given a collection of two dimensional points and a number k, return the k closest points to (0,0) by Euclidean distance.

* Reporting issues
How do I report a problem with Facebook?Facebook Advertising Help, Tips & Support | Facebook for Business provide facebook help center number ?

* Find patterns
Given a string as input, return the list of all the patterns possible:


'1' : ['A', 'B', 'C'],
'2' : ['D', 'E'],
'12' : ['X']
'3' : ['P', 'Q']
Example if input is '123', then output should be [ADP, ADQ, AEP, AEQ, BDP, BDQ, BEP, BEQ, CDP, CDQ, CEP, CEQ, XP, XQ]

* Moving in-place
Move[inplace] the non zero elements at the one end(end of array) and return the numbers of non zero elements in output array

* Question 2: Given a number 'k', return the corresponding row, given the pattern:
k => output
0 => []
1 => ["0", "1", "8"]
2 => ["00", "11", "69", "96", "88"]
3 => ["000", "111", "101", "888", ...] // and so on ...

* String
Question 1: Given an input of an array of string, verify if, turned 180 degrees, it is the "same".
For instance:
[1, 6, 0, 9, 1] => return true
[1, 7, 1] => return false

* Regex
Given a string "L*&EVe)))l", write a method which will determine if the input is a palindrome. Ignore all special characters. Uppercase/lowercase should be considered as same.

* Graph
Imagine a room full of people, with only 1 celebrity in the room. Celebrity is defined as a person who does not know anyone, but everyone knows him/her. Write a method who will take array of people and a person as input and return boolean if the person is a celebrity or not.

Solution : https://www.geeksforgeeks.org/move-zeroes-end-array/
